sudo: false

language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "4.0"
  - "4.1"
  - "4.2"

env:
  - CXX="g++-4.8"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8

script: docker run -it --link integration_web_1:aut razielt/taurus:jmeter
